name: bikeshare-data
channels:
  - conda-forge
dependencies:
  - python=3.8*
  - flake8
  - ipython
  - jupyterlab
  - black
  - requests
  - beautifulsoup4
  - click
  - pandas
  - psycopg2
  - sqlalchemy
  - geopandas
  - geoalchemy2
  - python-dotenv
  - openpyxl
  - xlsxwriter
  - pip
  - pip:
      - --editable .
